FROM python:3.13-alpine

RUN apk add --no-cache gcc musl-dev libffi-dev

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root

COPY ./src ./src
COPY ./example_datas ./example_datas
COPY ./nginx ./nginx
COPY ./llm_internal_api.py ./llm_internal_api.py

CMD ["uvicorn", "llm_internal_api:app", "--host", "0.0.0.0", "--port", "9000"]